version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/public:/etc/public
      - /etc/letsencrypt:/etc/letsencrypt
      - /root/nginx/conf.d:/etc/nginx/conf.d
    links:
      - green_rails
      - blue_rails

  redis:
    image: redis:alpine
    volumes:
      - /root/redis/data:/data
    command: redis-server --appendonly yes

  postgres_db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: testapp_user
      POSTGRES_PASSWORD: testapp_pass
      POSTGRES_DB: mytest
    volumes:
      - /root/postgres/data:/var/lib/postgresql/data
      - /usr/share/zoneinfo:/usr/share/zoneinfo

  green_rails:
    image: reg.file-converter.online:5000/pdf_app
    environment:
      SECRET_KEY_BASE: dsf9sdfsdf7sdf
      POSTGRES_USER: testapp_user
      POSTGRES_PASSWORD: testapp_pass
      POSTGRES_DB: mytest
      POSTGRES_HOST: postgres_db
      REDIS_URL: "redis://redis:6379"
    restart: always
    volumes:
      - /root/public:/rails_app/public
      - /root/rails/rails-entrypoint.sh:/rails_app/rails-entrypoint.sh
    volumes_from:
      - green_busybox
    links:
      - postgres_db
      - redis
    depends_on:
      - postgres_db
      - redis
      - green_busybox
    entrypoint: ./rails-entrypoint.sh
    command: bundle exec puma -C config/puma_production.rb -v

  blue_rails:
    image: reg.file-converter.online:5000/pdf_app
    environment:
      SECRET_KEY_BASE: dsf9sdfsdf7sdf
      POSTGRES_USER: testapp_user
      POSTGRES_PASSWORD: testapp_pass
      POSTGRES_DB: mytest
      POSTGRES_HOST: postgres_db
      REDIS_URL: "redis://redis:6379"
    restart: always
    volumes:
      - /root/public:/rails_app/public
      - /root/rails/rails-entrypoint.sh:/rails_app/rails-entrypoint.sh
    volumes_from:
      - blue_busybox
    links:
      - postgres_db
      - redis
    depends_on:
      - postgres_db
      - redis
      - blue_busybox
    entrypoint: ./rails-entrypoint.sh
    command: bundle exec puma -C config/puma_production.rb -v

  green_busybox:
    image: busybox
    volumes:
      - /bundle

  blue_busybox:
    image: busybox
    volumes:
      - /bundle
