default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pdf_app_development
test:
  <<: *default
  database: pdf_app_test

production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV['POSTGRES_DB'] %>
  host:     <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
